/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../../types.js';
import { BRAINSTORM_ROOT_WORKFLOW_SEQUENCE_BLOCK } from './superpowers-openspec-mapping.js';

const APPLY_EXECUTION_PLAN_GATE_STEP = (
  rerunInstruction: string
): string => `6. **Gate on execution plan before implementation loop** (brainstorm-root)

   **Canonical apply policy:** When \`schemaName\` is \`brainstorm-root\`, follow \`schemas/brainstorm-root/schema.yaml\` → \`apply\` → \`instruction\` in lockstep with the CLI output from \`openspec instructions apply --change "<name>" --json\`. The bullets below restate that block so agents do not skip pre-flight, executor choice, or transitive skill rules.

   Before implementation starts, check for:
   - \`openspec/changes/<name>/execution-plan.md\`

   If missing, pause and ask the user to run \`/opsx:writing-plans\` (or \`openspec-writing-plans\`) and save \`execution-plan.md\` at that path, then rerun ${rerunInstruction}.

   Clarify execution mode:
   - \`execution-plan.md\` is the source of truth for implementation step order (not \`plan.md\` or \`docs/superpowers/plans/\`)
   - Mark task checkboxes in \`tasks.md\` (\`- [ ]\` -> \`- [x]\`)

   **0. Pre-flight — verify required Superpowers skills** (same as schema \`apply.instruction\`):

   This schema's apply phase requires the following skills. Confirm each appears in your available skills list before proceeding:

   - \`superpowers:subagent-driven-development\` (transitively: \`superpowers:test-driven-development\`, \`superpowers:requesting-code-review\`)

   If any required skill is missing, STOP and inform the user — do NOT proceed and do NOT silently fall back to manual implementation. The user can install the Superpowers plugin, or explicitly opt into the manual fallback path described at the end of the dynamic apply instruction from the CLI (when present).

   **1. Executor — subagent-driven-development** (same as schema \`apply.instruction\`):

   Use the Skill tool to invoke **superpowers:subagent-driven-development** to execute the \`execution-plan.md\` micro-tasks with fresh subagents per task.

   Tell the executor:
   - Read \`execution-plan.md\` in this change directory for micro-tasks
   - Update \`tasks.md\` checkboxes as coarse tasks complete
   - Do **not** run \`git commit\` while executing \`superpowers:subagent-driven-development\` for this brainstorm-root apply flow unless the user explicitly asks for a commit; track progress with \`tasks.md\` checkboxes and working-tree changes only.

   **IMPORTANT — transitive skill activation:** \`subagent-driven-development\` internally enforces the following skills, so you do NOT need to invoke them manually:
   - **superpowers:test-driven-development** — every task follows RED-GREEN-REFACTOR. Implementation code written before a failing test is deleted.
   - **superpowers:requesting-code-review** — after each task, a code-reviewer subagent is dispatched to catch spec compliance and code quality issues. A final review runs for the entire implementation before apply concludes.

   This schema does NOT support \`superpowers:executing-plans\` as a fallback for non-subagent platforms. Per its SKILL.md, \`executing-plans\` does not transitively activate TDD or code-review — defeating the rigor that Superpowers brings. If your platform lacks subagent support, use the built-in \`spec-driven\` schema instead of this one.

   Implementation scale:
   - **Small, narrowly scoped work:** continue inline in this session while still honoring \`execution-plan.md\` ordering and checkbox updates.

   **Do not** default to \`using-git-worktrees\` for OpenSpec apply flows unless the user **explicitly** asks for isolated git worktrees.`;

export function getBrainstormRootApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement tasks from an OpenSpec change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: `Implement tasks from an OpenSpec change.

${BRAINSTORM_ROOT_WORKFLOW_SEQUENCE_BLOCK}

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:apply <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifact contains the tasks (typically "tasks" for spec-driven, check status for others)

3. **Get apply instructions**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - \`contextFiles\`: artifact ID -> array of concrete file paths (varies by schema - could be proposal/specs/design/tasks or spec/tests/implementation/docs)
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message; if \`schemaName\` is \`brainstorm-root\`, map the blocker to the next slash step (\`/opsx:brainstorm\`, \`/opsx:continue\`, or \`/opsx:writing-plans\` as appropriate) using the workflow sequence above; otherwise suggest \`/opsx:continue\` or the CLI output.
   - If \`state: "all_done"\`: congratulate, suggest archive
   - Otherwise: proceed to implementation

4. **Read context files**

   Read every file path listed under \`contextFiles\` from the apply instructions output.
   The files depend on the schema being used:
   - **spec-driven**: proposal, specs, design, tasks
   - Other schemas: follow the contextFiles from CLI output

5. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

${APPLY_EXECUTION_PLAN_GATE_STEP('apply')}

7. **Implement tasks (loop until done or blocked)**

   For each pending task:
   - Show which task is being worked on
   - Make the code changes required
   - Keep changes minimal and focused
   - Mark task complete in the tasks file: \`- [ ]\` → \`- [x]\`
   - Continue to next task

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Error or blocker encountered → report and wait for guidance
   - User interrupts

8. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! Ready to archive this change.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles from CLI output, don't assume specific file names

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBrainstormRootApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Apply',
    description: 'Implement tasks from an OpenSpec change (Experimental)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Implement tasks from an OpenSpec change.

${BRAINSTORM_ROOT_WORKFLOW_SEQUENCE_BLOCK}

**Input**: Optionally specify a change name (e.g., \`/opsx:apply add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:apply <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifact contains the tasks (typically "tasks" for spec-driven, check status for others)

3. **Get apply instructions**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - \`contextFiles\`: artifact ID -> array of concrete file paths (varies by schema)
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message; if \`schemaName\` is \`brainstorm-root\`, map the blocker to the next slash step (\`/opsx:brainstorm\`, \`/opsx:continue\`, or \`/opsx:writing-plans\` as appropriate) using the workflow sequence above; otherwise suggest \`/opsx:continue\` or the CLI output.
   - If \`state: "all_done"\`: congratulate, suggest archive
   - Otherwise: proceed to implementation

4. **Read context files**

   Read every file path listed under \`contextFiles\` from the apply instructions output.
   The files depend on the schema being used:
   - **spec-driven**: proposal, specs, design, tasks
   - Other schemas: follow the contextFiles from CLI output

5. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

${APPLY_EXECUTION_PLAN_GATE_STEP('`/opsx:apply`')}

7. **Implement tasks (loop until done or blocked)**

   For each pending task:
   - Show which task is being worked on
   - Make the code changes required
   - Keep changes minimal and focused
   - Mark task complete in the tasks file: \`- [ ]\` → \`- [x]\`
   - Continue to next task

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Error or blocker encountered → report and wait for guidance
   - User interrupts

8. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! You can archive this change with \`/opsx:archive\`.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles from CLI output, don't assume specific file names

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`
  };
}
