/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../../types.js';
import {
  BRAINSTORM_ROOT_GATE_POLICY_BLOCK,
  BRAINSTORM_ROOT_WORKFLOW_SEQUENCE_BLOCK,
} from './superpowers-openspec-mapping.js';

export function getBrainstormRootProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: `Propose a new change - create the change and generate all artifacts in one step.

Generate artifacts from current schema status:
- For brainstorm-root, start with \`brainstorm.md\`; include \`design.md\` only when needed.
- Do not assume proposal-first sequencing. Derive the next artifact from \`openspec status --change "<name>" --json\`, artifact dependencies, and \`applyRequires\`.
- Never create \`plan\` (\`execution-plan.md\`) in propose; hand off to \`/opsx:writing-plans\`.
- In brainstorm-root propose flow, use \`--schema brainstorm-root\` on schema-sensitive CLI calls.

When all non-plan requirements are done:
- Brainstorm-root: prompt \`/opsx:writing-plans\` (or \`openspec-writing-plans\`) before \`/opsx:apply\`.
- Other schemas: follow status output for next step.

${BRAINSTORM_ROOT_WORKFLOW_SEQUENCE_BLOCK}

${BRAINSTORM_ROOT_GATE_POLICY_BLOCK}

---

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   This creates a scaffolded change at \`openspec/changes/<name>/\` with \`.openspec.yaml\`.

3. **Get schema-aware artifact build order**
   \`\`\`bash
   openspec status --change "<name>" --schema brainstorm-root --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

4. **Create artifacts in sequence until writing-plans handoff**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts using status JSON:
   - Prioritize artifacts with \`status: "ready"\` (dependencies satisfied)
   - Never infer fixed filenames from another schema; use \`artifact.id\`, \`instruction\`, and \`outputPath\`

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<name>" --schema brainstorm-root --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all non-plan \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`openspec status --change "<name>" --json\`
   - Build a target set from \`applyRequires\`, excluding \`plan\`
   - Check if every artifact ID in that target set has \`status: "done"\` in the artifacts array
   - Stop when all target artifacts are done; do NOT create \`plan\` here

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

5. **Show final status**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for execution planning."
- Prompt (brainstorm-root): "Run \`/opsx:writing-plans\`, ensure \`openspec/changes/<name>/execution-plan.md\`, then run \`/opsx:apply\`."

**Artifact Creation Guidelines**

- Treat \`openspec instructions ... --json\` as source-of-truth for each artifact.
- Read dependencies first; use \`template\` to structure output.
- Apply \`context\` and \`rules\` as constraints only (never copy them into the artifact file).

**Guardrails**
- Create artifacts needed before writing-plans; for brainstorm-root, never auto-create \`plan\` in this flow
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- If operating in brainstorm-root and \`--schema brainstorm-root\` is missing on schema-sensitive commands, STOP and rerun with the explicit schema flag.
- If \`plan\` is the only remaining required artifact, STOP and instruct the user to run \`/opsx:writing-plans\`.
- Verify each artifact file exists after writing before proceeding to next`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBrainstormRootProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Propose a new change - create it and generate all artifacts in one step',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Propose a new change - create the change and generate all artifacts in one step.

Generate artifacts from current schema status:
- For brainstorm-root, start with \`brainstorm.md\`; include \`design.md\` only when needed.
- Do not assume proposal-first sequencing. Derive the next artifact from \`openspec status --change "<name>" --json\`, artifact dependencies, and \`applyRequires\`.
- Never create \`plan\` (\`execution-plan.md\`) in propose; hand off to \`/opsx:writing-plans\`.
- In brainstorm-root propose flow, use \`--schema brainstorm-root\` on schema-sensitive CLI calls.

When all non-plan requirements are done:
- Brainstorm-root: prompt \`/opsx:writing-plans\` (or \`openspec-writing-plans\`) before \`/opsx:apply\`.
- Other schemas: follow status output for next step.

${BRAINSTORM_ROOT_WORKFLOW_SEQUENCE_BLOCK}

${BRAINSTORM_ROOT_GATE_POLICY_BLOCK}

---

**Input**: The argument after \`/opsx:propose\` is the change name (kebab-case), OR a description of what the user wants to build.

**Steps**

1. **If no input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   This creates a scaffolded change at \`openspec/changes/<name>/\` with \`.openspec.yaml\`.

3. **Get schema-aware artifact build order**
   \`\`\`bash
   openspec status --change "<name>" --schema brainstorm-root --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

4. **Create artifacts in sequence until writing-plans handoff**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts using status JSON:
   - Prioritize artifacts with \`status: "ready"\` (dependencies satisfied)
   - Never infer fixed filenames from another schema; use \`artifact.id\`, \`instruction\`, and \`outputPath\`

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<name>" --schema brainstorm-root --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all non-plan \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`openspec status --change "<name>" --json\`
   - Build a target set from \`applyRequires\`, excluding \`plan\`
   - Check if every artifact ID in that target set has \`status: "done"\` in the artifacts array
   - Stop when all target artifacts are done; do NOT create \`plan\` here

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

5. **Show final status**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for execution planning."
- Prompt (brainstorm-root): "Run \`/opsx:writing-plans\`, ensure \`openspec/changes/<name>/execution-plan.md\`, then run \`/opsx:apply\`."

**Artifact Creation Guidelines**

- Treat \`openspec instructions ... --json\` as source-of-truth for each artifact.
- Read dependencies first; use \`template\` to structure output.
- Apply \`context\` and \`rules\` as constraints only (never copy them into the artifact file).

**Guardrails**
- Create artifacts needed before writing-plans; for brainstorm-root, never auto-create \`plan\` in this flow
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- If operating in brainstorm-root and \`--schema brainstorm-root\` is missing on schema-sensitive commands, STOP and rerun with the explicit schema flag.
- If \`plan\` is the only remaining required artifact, STOP and instruct the user to run \`/opsx:writing-plans\`.
- Verify each artifact file exists after writing before proceeding to next`
  };
}
